name: run portfolio

on: [push]

jobs:
  protfolio :
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build project using compose
        run: docker compose up -d --build

      - name: Test Frontend
        run: curl http://localhost:7000